
package metodobiseccion;


import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.*;


 //* @author Yael

public class Principal extends javax.swing.JFrame implements Runnable{
    String hora, minutos;
    Thread hilo;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
         this.setLocationRelativeTo(null);
        Fecha.setText(fecha());
        
        hilo= new Thread(this);
        hilo.start();
        setVisible(true);
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/f1.jpg")));
        
    }
    
    public void hora(){
        Calendar calendario = new GregorianCalendar();
        Date horaactual=new Date();
        calendario.setTime(horaactual);
        hora=calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        minutos= calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
    }
     public void run(){
         Thread current= Thread.currentThread();
         while(current== hilo){
             hora();
             Hora.setText(hora+":"+minutos);
}
         
     }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        BtnGaussmejorado = new javax.swing.JButton();
        Hora = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        BtnSalida = new javax.swing.JButton();
        BtnBiseccion1 = new javax.swing.JButton();
        BtnGauss = new javax.swing.JButton();
        NewtonRap = new javax.swing.JButton();
        BtnNewton2do = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(102, 0, 102)));
        jPanel3.setMaximumSize(new java.awt.Dimension(1000, 562));
        jPanel3.setMinimumSize(new java.awt.Dimension(1000, 562));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Métodos Numéricos");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jLabel2);
        jLabel2.setBounds(230, 80, 340, 50);

        Fecha.setBackground(new java.awt.Color(255, 204, 204));
        Fecha.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        Fecha.setForeground(new java.awt.Color(255, 255, 255));
        Fecha.setText("DD / MM / YYYY");
        Fecha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(Fecha);
        Fecha.setBounds(600, 0, 210, 60);

        BtnGaussmejorado.setBackground(new java.awt.Color(255, 102, 204));
        BtnGaussmejorado.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
        BtnGaussmejorado.setForeground(new java.awt.Color(255, 255, 255));
        BtnGaussmejorado.setText("Gauss-jordan mejorado");
        BtnGaussmejorado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGaussmejoradoActionPerformed(evt);
            }
        });
        jPanel3.add(BtnGaussmejorado);
        BtnGaussmejorado.setBounds(50, 290, 310, 50);

        Hora.setBackground(new java.awt.Color(255, 204, 204));
        Hora.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        Hora.setForeground(new java.awt.Color(255, 255, 255));
        Hora.setText("00:00");
        jPanel3.add(Hora);
        Hora.setBounds(50, 0, 210, 60);

        jPanel4.setBackground(new java.awt.Color(204, 153, 255));
        jPanel4.setLayout(new javax.swing.OverlayLayout(jPanel4));
        jPanel3.add(jPanel4);
        jPanel4.setBounds(10, 10, 760, 40);

        BtnSalida.setBackground(new java.awt.Color(0, 153, 153));
        BtnSalida.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
        BtnSalida.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalida.setText("Salir");
        BtnSalida.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalidaActionPerformed(evt);
            }
        });
        jPanel3.add(BtnSalida);
        BtnSalida.setBounds(30, 400, 110, 50);

        BtnBiseccion1.setBackground(new java.awt.Color(255, 102, 204));
        BtnBiseccion1.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
        BtnBiseccion1.setForeground(new java.awt.Color(255, 255, 255));
        BtnBiseccion1.setText("Metodo de Biseccion");
        BtnBiseccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBiseccion1ActionPerformed(evt);
            }
        });
        jPanel3.add(BtnBiseccion1);
        BtnBiseccion1.setBounds(50, 140, 310, 50);

        BtnGauss.setBackground(new java.awt.Color(255, 102, 204));
        BtnGauss.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
        BtnGauss.setForeground(new java.awt.Color(255, 255, 255));
        BtnGauss.setText("Gauss");
        BtnGauss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGaussActionPerformed(evt);
            }
        });
        jPanel3.add(BtnGauss);
        BtnGauss.setBounds(410, 220, 310, 50);

        NewtonRap.setBackground(new java.awt.Color(255, 102, 204));
        NewtonRap.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
        NewtonRap.setForeground(new java.awt.Color(255, 255, 255));
        NewtonRap.setText("Newton Raphson");
        NewtonRap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewtonRapActionPerformed(evt);
            }
        });
        jPanel3.add(NewtonRap);
        NewtonRap.setBounds(410, 140, 310, 50);

        BtnNewton2do.setBackground(new java.awt.Color(255, 102, 204));
        BtnNewton2do.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
        BtnNewton2do.setForeground(new java.awt.Color(255, 255, 255));
        BtnNewton2do.setText("Newton Raphson 2do orden");
        BtnNewton2do.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNewton2doActionPerformed(evt);
            }
        });
        jPanel3.add(BtnNewton2do);
        BtnNewton2do.setBounds(50, 220, 310, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnSalidaActionPerformed

    private void BtnGaussmejoradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGaussmejoradoActionPerformed
        
       /* Biseccion newframe = new Biseccion();
        newframe.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_BtnGaussmejoradoActionPerformed

    private void BtnBiseccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBiseccion1ActionPerformed
        // TODO add your handling code here:
         Biseccion newframe = new Biseccion();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnBiseccion1ActionPerformed

    private void BtnGaussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGaussActionPerformed
        // TODO add your handling code here:
         Gauss newframe = new Gauss();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnGaussActionPerformed

    private void NewtonRapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewtonRapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewtonRapActionPerformed

    private void BtnNewton2doActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNewton2doActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNewton2doActionPerformed

    /**
     * @param args the command line arguments
     */
    public static String fecha(){
        Date fecha= new Date();
        SimpleDateFormat formatofecha= new SimpleDateFormat("dd / MMM / YYYY");
      
        return formatofecha.format(fecha);
        
    }
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
        
    }

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBiseccion1;
    private javax.swing.JButton BtnGauss;
    private javax.swing.JButton BtnGaussmejorado;
    private javax.swing.JButton BtnNewton2do;
    private javax.swing.JButton BtnSalida;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Hora;
    private javax.swing.JButton NewtonRap;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
